version: "3.7"
services:
  mysqldb:
    container_name: mysql_db
    image: mysql:latest
    ports:
      - '3808:3808'
    environment:
      - MYSQL_ROOT_PASSWORD=develop
      - MYSQL_DATABASE=app
      - MYSQL_TCP_PORT=3808

  app:
    build:
      args:
        user: thiago
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: 'php:8.1.2-fpm'
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: php-docker
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    environment:
      APPLICATION_ENV: development
      XDEBUG_INSTALL: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      XDEBUG_REMOTE_ENABLE: "on"
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HANDLER: dbgp
      XDEBUG_PROFILER_ENABLE: 1
      XDEBUG_PROFILER_OUTPUT_DIR: /var/www/html/xdebug.log
      XDEBUG_REMOTE_PORT: 9003
      XDEBUGINI_PATH: /usr/local/etc/php/conf.d/xdebug.ini
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_IDEKEY: PHPSTORM
    depends_on:
      - mysqldb

  nginx:
    image: nginx:alpine
    container_name: docker-nginx
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app

  